### ISSUE TITLE
Exception Data property is not exist on Seq

### ISSUE THREAD

**Issue by cilerler** [datalust/seq-extensions-logging#12]
Following code

```csharp
var exception = new Exception("USPS API error 'Invalid Address.  '");
exception.Data.Add("payload", address); //object
exception.Data.Add("response", xmlResponse); //string
_logger.LogError(-1, nex, "An error occured");
```
generates an output as 

![image](https://cloud.githubusercontent.com/assets/385958/20359371/8672df36-abfd-11e6-84fd-0118c327134e.png)

where it should also include **Data** in the fields.

**Comment by nblumhardt** [comment]
Thanks for the note. This one's a little tricky since the `Exception` might be an `AggregateException`, and each exception within the aggregate have data, and so-on. I might take a look at how _SerilogExceptions_ handles this case and see if there's a sensible default we could use here 👍

**Comment by cilerler** [comment]
It looks like it doesn't provide **Internal Exceptions** neither which is fine, but not having **Data** forces my hand to keep adding additional code to push debugging variables and even worse have to do round-trip to find that data after filtering the error.

**Comment by cilerler** [comment]
This is definitely one of the very important missing point.  🤓

instead of code below

```csharp
catch (Exception ex)
{
    ex.Data.Add("key", _keyAuthentication);
    _logger.LogError(-1, ex, ex.Message);
}
```

I have to write like this 😱

```csharp
catch (Exception ex)
{
    _logger.LogError(-1, ex, $"{ex.Message} {{key}}", _keyAuthentication);
}
```

You may say it is not that bad, well for a single variable yes but if it will be 10 variables it would be very ugly. 🙄

**Comment by cilerler** [comment]
By the way, my 2 cents says you should add **Data** fields on top of RED exception box above the stack trace. 😎

**Comment by cilerler** [comment]
is there any chance you may put this enhancement to in-front of the line? 😊
