### ISSUE TITLE
Support enrichers

### ISSUE THREAD

**Issue by ipzKellyR** [datalust/seq-extensions-logging#28]
The setup for this is great because its one line and then add a config section, but using this method you cannot easily add enrichers. Am I mistaken?

**Comment by nblumhardt** [comment]
Thanks for the note. This package wraps up and completely internalizes these bits of Serilog, and it would probably be confusing to expose interfaces like `ILogEventEnricher`, but, some cut-down enrichment functionality seems useful enough to include.

Which enrichers in particular did you have in mind?

**Comment by ipzKellyR** [comment]
would it be possible to allow someone to pass enrichers in as options?

**Comment by nblumhardt** [comment]
Probably not via `ILogEventEnricher`, but something like `Func<(string, object)>` could be used to provide simple enrichment from ambient state, without necessitating exposure of types like `LogEvent`, `LogEventPropertyValue` and so on. Would that work in your case?

```csharp
    .AddSeq(..., () => ("ThreadId", Thread.CurrentThread.ManagedThreadId))
```

(We'd need to figure out a workable API to allow for multiple enrichers to be passed, but the above might illustrate the basic idea..)

**Comment by danbopes** [comment]
@nblumhardt Any chance we can get this implemented. I hate to switch my entire logger over to serilog just to add this feature, but having hostname or the managedthreadid on each log entry would be super helpful.

**Comment by nblumhardt** [comment]
Thanks for the nudge, @danbopes; I'm taking another look at this now.

**Comment by danbopes** [comment]
@nblumhardt I ended up adding serilog but only as a logging provider to .net core, which honestly wasn't as bad as I thought. This case I could already leverage all of the .net core `ILogger` features without having to rewrite a ton of code:

```
builder.Services.AddLogging(loggingBuilder =>
{
    var serverUrl = builder.Configuration.GetValue<string>("Logging:Seq:ServerUrl");
    var apiKey = builder.Configuration.GetValue<string>("Logging:Seq:ApiKey");

    var logger = new LoggerConfiguration()
        .Enrich.WithAssemblyInformationalVersion()
        .Enrich.WithMachineName()
        .MinimumLevel.Verbose()
        .WriteTo.Console(Serilog.Events.LogEventLevel.Information)
        .WriteTo.Seq(serverUrl, apiKey: apiKey)
        .CreateLogger();

    loggingBuilder.AddSerilog(logger, true);
});
```

My only pain point now, is simply having to convert json back to a structure to be reencoded with json again.

**Comment by nblumhardt** [comment]
Thanks for the update @danbopes. `UseSerilog()` still supports .NET's `ILogger`, just in case that helps (`UseSerilog()` is generally a bit more predictable when it comes to levels/filters).

**Comment by BrianVallelunga** [comment]
Call it an enricher if you want, but it would be nice to be able to just add a few items to the global logging scope supported by ILogger's BeginScope(). I'm specifically looking to add something like a version number or application name.

**Comment by nblumhardt** [comment]
I've kicked off some work on this; I think because it'll be best if accessible via JSON configuration, it's a good time to overhaul how the sink is configured, so that's the first cab off the rank. I'll keep this thread updated as I go :-)

**Comment by w5l** [comment]
What speaks against simply opening up `ILogEventEnricher` (or a variant of it) to dependency injection? We could then register any enricher implementation with DI and have it injected, keeping configuration simple. Adding a default implementation of `EnvironmentValueEnricher` and/or `StaticValueEnricher` to the library would cover most people's requirements.

`services.AddSingleton<ILogEventEnricher>(() => new StaticValueEnricher("..."));`

This matches part of the `ITelemetryProcessor` pattern in use by Azure AppInsights, see [Filter and preprocess telemetry in the Application Insights SDK](https://learn.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling). Even more powerful, this allows post processing _and filtering_ of the entire log message. A basic `ILogProcessor.Process(LogEvent event, Func<LogEvent> next);` would cover pretty much every possible use case.

**Comment by nblumhardt** [comment]
@w5l this is already implemented via `ReadFrom.Services(serviceCollection)`, check out the _Serilog.AspNetCore_ examples to see how it's used (IIRC).

`ReadFrom.Services()` supports sinks, filters, enrichers, and destructuring policies. HTH!

**Comment by nblumhardt** [comment]
@w5l  sorry, I see I'm in `datalust-extensions-logging` and not `serilog-extensions-logging`, which I also maintain 😅

**Comment by w5l** [comment]
No worries, a little shock there thinking I've overseen something glaringly obvious 🙈 but yeah, like the people before me in this thread I was hoping to have this supported in the datalust-seq version without using full-blown serilog.

**Comment by amitjaura** [comment]
@nblumhardt  - Just checking if this is in the pipeline. It will be nice to have enrichers setup along with Seq. I like the idea of 

`    .AddSeq(..., () => ("ThreadId", Thread.CurrentThread.ManagedThreadId))`

**Comment by nblumhardt** [comment]
Thanks for the nudge @amitjaura, I'll try to loop back to this soon.

**Comment by KodrAus** [comment]
I'm having a look at implementing this over the week. This particular codebase is pretty new to me but I think the main thing we want to avoid is exposing any of the vendored Serilog internals through public APIs. That makes the more general middleware approach of `ILogProcessor.Process(LogEvent event, Func<LogEvent> next);` which I otherwise quite like less appealing.

Ignoring configuration for now, I think our two main options are:

1. `Func<(string, object)>` or `Func<IReadOnlyDictionary<string, object>>` for an enricher that returns state to the caller to enrich the underlying log event with.
2. `Action<IPropertyCollection>` where `IPropertyCollection` wraps up the `LogEvent` and exposes some niceties like `AddIfAbsent`. It would also do the translation of an `object` into a `PropertyValue`.

I think my preference is for 2. here. It gives us more flexibility to enhance the API over time and potentially avoids unnecessary allocation for enrichers that want to deal with multiple properties.

I am also happy with the original `Func<(string, object)>` approach, which is nicely minimal, and prevents the API from evolving past its original scope.

Thoughts?

**Comment by nblumhardt** [comment]
I'm also pretty keen on (2) 👍

**Comment by KodrAus** [comment]
I've opened up #61 that supports this using a variant of 2. I described earlier. It adds an optional `IEnumerable<Action<EnrichingEvent>> enrichers` parameter to `AddSeq`, where `EnrichingEvent` is a wrapper around `LogEvent` that exposes some of its functionality. With a collection expression it looks something like this:

```csharp
AddSeq(enrichers: [
    // Simple scalar value
    (evt) => evt.AddOrUpdateProperty("A", 1),
    // Destructured object
    (evt) => evt.AddOrUpdateProperty("B", new { a: 1 }, true)
]))
```
