### ISSUE TITLE
  Apikey doesn't work. If it is set incorrectly or not configured, it can be written into the log normally

### ISSUE THREAD

**Issue by wg296613796** [datalust/seq-extensions-logging#48]

**Comment by nblumhardt** [comment]
Hi! Thanks for getting in touch. Do you have "Require authentication for HTTP/S ingestion" set in the _Settings > API keys_ screen?

**Comment by wg296613796** [comment]
yes，I set the ApiKey in Settings-&gt;APIKeys,but it doesnot work,and logs can be written without setting APIKEY in the configuration,so i think this is a bug



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "datalust/seq-extensions-logging"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月12日(星期一) 中午11:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [datalust/seq-extensions-logging]   Apikey doesn't work. If it is set incorrectly or not configured, it can be written into the log normally (#48)





 
Hi! Thanks for getting in touch. Do you have "Require authentication for HTTP/S ingestion" set in the Settings &gt; API keys screen?

**Comment by nblumhardt** [comment]
Hi, thanks for your reply. It's not the API key itself that I'm referring to, but a checkbox that looks like:

![image](https://user-images.githubusercontent.com/342712/125228381-ff2fae80-e317-11eb-97f8-b3aaf09c4818.png)

**Comment by wg296613796** [comment]
ok，i tried,it works,thank you!
But i have one more question: How can I filter out the log by the ApiKey, I have multiple applications and ApiKeys


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "datalust/seq-extensions-logging"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月12日(星期一) 中午11:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [datalust/seq-extensions-logging]   Apikey doesn't work. If it is set incorrectly or not configured, it can be written into the log normally (#48)





 
Hi, thanks for your reply. It's not the API key itself that I'm referring to, but a checkbox that looks like:

**Comment by nblumhardt** [comment]
Thanks great 👍 

To filter by API key, go the the settings for an API key, and in the "Applied Properties" box, add some properties to search on - e.g. `Source = Service1`.

You can then use those properties as filters in the Events screen, e.g. `Source = 'Service1`, and create signals from them if you find you're using the same searches a lot.

Hope this helps!

**Comment by wg296613796** [comment]
Ok,I get,thank you very much!^_^
